#!/usr/bin/env bash

mkdir -p ~/.tibia;
if [ "${1}" = '--no-markers' ]; then
	echo 'Downloading & extracting `Automap-without-markers.zip` to `~/.local/share/CipSoft\ GmbH/Tibia/packages/Tibia/ `…';
	url='https://tibiamaps.io/downloads/minimap-without-markers';
else
	echo 'Downloading & extracting `Automap-with-markers.zip` to `~/.local/share/CipSoft\ GmbH/Tibia/packages/Tibia/ `…';
	url='https://tibiamaps.io/downloads/minimap-with-markers';
fi;
zip_file_name="$(mktemp)";
curl --progress-bar --location "${url}" > "${zip_file_name}";
unzip -o -d ~/.local/share/CipSoft\ GmbH/Tibia/packages/Tibia/ "${zip_file_name}";
rm "${zip_file_name}";
